name: Docker Build and Push for Rust App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the Docker image version (e.g., 0.1.0)"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ inputs.version }}
        docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }} ghcr.io/${{ github.repository }}:latest

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ inputs.version }}
        docker push ghcr.io/${{ github.repository }}:latest
